"""Restore selected Hexo HTML articles from an exported legacy commit.
Usage: python scripts/migrate.py LEGACY_DIRECTORY IMAGE_REPOSITORY
Requires beautifulsoup4==4.15.0 and markdownify==1.2.3.
"""
from pathlib import Path
import sys, json, shutil, re, xml.etree.ElementTree as ET
from urllib.parse import urlsplit, unquote
from bs4 import BeautifulSoup
from markdownify import markdownify

root=Path(__file__).resolve().parents[1]
legacy, images=map(Path,sys.argv[1:])
exclude={
'an-essential-application-for-writing-blogs-on-android':'用户要求精简低信息量内容：应用推荐截图，无具体技术分析',
'baidu-network-disk-speed-limit-cracking-solution':'用户要求精简低信息量内容：下载方案罗列，无操作实现',
'modapks':'用户要求精简低信息量内容：应用下载合集',
'android-signature-file-replacement-notice':'用户明确要求删除签名更换通知',
'blog-beautification-log':'用户明确要求删除整篇',
'a-conservation-water-problem-of-competitive-momentum-and-angular':'高中物理 / 物理竞赛',
'superlevel-college-entrance-examination-physics-questions':'高中物理 / 物理竞赛',
'comparison-of-linear-motion-particle-and-rotation-rigid-body':'高中物理 / 物理竞赛',
'how-to-set-up-a-broom-scientifically':'物理科普，且包含引用内容',
'java-code-streamlining':'明确转载：阿里巴巴中间件，作者常意',
'some-frequently-used-java-code':'原文声明混合网络代码与原创，无法区分来源',
'biological-compulsory-two-outline':'高中生物学习资料，非技术内容',
'todolist':'高中学习待办，非技术内容',
'page-not-found':'日常纪念文章，非技术内容',
'hello-world':'旧站欢迎页，非技术文章',
}
descriptions={
'android-signature-file-replacement-notice':'旧 Android 项目的签名变更记录。',
'bmap-v7072-crack':'Bmap 7.0.72 的本地会员状态判断分析与修改记录。',
'baidu-network-disk-speed-limit-cracking-solution':'2020 年整理的网盘下载方案及使用体验。',
'blog-beautification-log':'记录旧 Hexo 博客的背景切换、夜间模式与界面调整。',
'modapks':'曾参与开发或修改的 Android 应用记录。',
'an-essential-application-for-writing-blogs-on-android':'在 Android 设备上维护博客的工具与操作截图。',
'how-to-create-an-explosive-personal-blog-on-your-android-phone':'使用 Termux、Hexo 和 GitHub Pages 在 Android 手机上搭建博客。',
'snpcrack':'早期少年派 Android 平板的设备管理与调试记录。',
'qq-browser-signature-verification-crack':'QQ 浏览器旧版本的签名校验分析记录。',
}
ns={'a':'http://www.w3.org/2005/Atom'}
entries={urlsplit(e.find('a:link',ns).get('href')).path:e for e in ET.parse(legacy/'atom.xml').findall('a:entry',ns)}
# Remove only previously generated legacy posts, so changed exclusions are applied on rerun.
for previous in (root/'content/posts').glob('*.md'):
 try:
  metadata, _ = json.JSONDecoder().raw_decode(previous.read_text())
 except ValueError:
  continue
 if metadata.get('legacy') is True:
  previous.unlink()
# This directory contains only images generated by this migration.
if (root/'static/images/legacy').exists():
 shutil.rmtree(root/'static/images/legacy')
report=[]
(root/'content/posts').mkdir(parents=True,exist_ok=True)
for p in sorted(legacy.glob('20*/*.html')):
 s=BeautifulSoup(p.read_text(),'html.parser'); b=s.select_one('.markdown-body'); title=s.title.get_text().split(' ~ ')[0]; url='/'+p.relative_to(legacy).as_posix()
 row={'title':title,'url':url,'status':'excluded' if p.stem in exclude else 'kept','reason':exclude.get(p.stem,'技术内容；未见整篇转载声明')}
 report.append(row)
 if row['status']=='excluded':continue
 for el in b.select('a.markdownIt-Anchor,script,style'):el.decompose()
 for im in b.select('img'):
  source=im.get('data-src') or im.get('src',''); match=re.match(r'https?://cdn.jsdelivr.net/gh/wtrwx/wtrwxIMG/(.+)',source,re.I)
  if match:
   name=unquote(match.group(1)); src=images/name
   if not src.is_file():raise RuntimeError(f'Missing image: {src}')
   dest=root/'static/images/legacy'/name; dest.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(src,dest)
   im['src']='/images/legacy/'+name
  im['alt']=im.get('alt') or title+' · 截图'
 for a in b.select('a[href]'):
  u=urlsplit(a['href'])
  if u.hostname and u.hostname.lower()=='wtrwx.github.io':a['href']=u.path+('?' +u.query if u.query else '')+('#'+u.fragment if u.fragment else '')
 # Protect code verbatim: markdown conversion must not merge lines or escape operators.
 codes=[]
 for pre in b.select('pre'):
  code=pre.find('code'); language=(code.get('class') or [''])[0] if code else ''; txt=pre.get_text()
  fence='`'*max(3,1+max([len(x) for x in re.findall(r'`+',txt)] or [0])); token=f'ARCHIECODEBLOCK{len(codes)}TOKEN'
  codes.append((token,f'{fence}{language}\n{txt.rstrip()}\n{fence}'));pre.replace_with(BeautifulSoup('<p>'+token+'</p>','html.parser'))
 body=markdownify(str(b),heading_style='ATX',bullets='-').strip()
 for token,code in codes:body=body.replace(token,code)
 tags=list(dict.fromkeys(a.get_text(strip=True) for a in s.select('a[href^="/tags/"]') if a['href']!='/tags/'))
 e=entries.get(url); date=e.findtext('a:published',namespaces=ns) if e is not None else p.parent.name[:4]+'-'+p.parent.name[4:6]+'-'+p.parent.name[6:]+'T00:00:00+08:00'
 meta={'title':title,'date':date,'url':url,'tags':tags,'description':descriptions[p.stem],'toc':len(b.select('h2,h3'))>=3,'legacy':True}
 (root/'content/posts'/f'{p.stem}.md').write_text(json.dumps(meta,ensure_ascii=False,indent=2)+'\n\n'+body+'\n')
for url,e in entries.items():
 if not (legacy/url.lstrip('/')).exists():report.append({'title':e.findtext('a:title',namespaces=ns),'url':url,'status':'not-restored','reason':'仅 RSS 残留，当前仓库没有对应页面，避免复活已移除内容'})
(root/'migration').mkdir(exist_ok=True)
(root/'migration/manifest.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
lines=['# 文章迁移清单','','来源：`Wtrwx/Wtrwx.github.io`，原始提交 `5a99b1ef`。','保留原文、发布日期、标签、文章 URL；图片从个人图床迁入本地。','按用户要求精简：保留 3 篇技术实践文章及用户指定恢复的少年派教程，共 4 篇。','','| 文章 | 处理 | 理由 |','|---|---|---|']
for r in report:lines.append(f"| {r['title']} | {r['status']} | {r['reason']} |")
lines+=['','## 回滚与恢复','','旧站完整内容仍在 Git 历史中。迁移未重写历史；可从原始提交导出。','`scripts/migrate.py` 可从旧站导出目录和图床仓库重新生成保留文章。','','## 旧工具页','','旧站 Hex2RGBA、OnlinePython、links、tools 等独立页面未纳入此次文章迁移。','旧 `/archives/` 重定向到文章列表；旧 `/atom.xml` 继续提供 Atom 订阅。']
(root/'migration/REPORT.md').write_text('\n'.join(lines)+'\n')
print('Migrated',sum(r['status']=='kept' for r in report),'articles;',len(list((root/'static/images/legacy').rglob('*'))),'images')
